version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

services:
  database:
    image: 'mongo'
    container_name: 'mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=training
      - MONGO_INITDB_ROOT_USERNAME=asgar
      - MONGO_INITDB_ROOT_PASSWORD=789801Asgar
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
    networks:
      - backend

  trainingBotTelegram:
    image: 'thorinhood/trainingbot'
    container_name: 'training-bot-telegram'
    depends_on:
      - database
    volumes:
      - ./logs:/logs
    ports:
      - '8080:8080'
      - '8090:8090'
    networks:
      - backend
      - frontend